### ISSUE TITLE
Combien de jour pour cette initiation.

### ISSUE THREAD

**Issue by LBdN** [MrFrangipane/initiation-python#1]
Bonjour, 
( Il n'y a pas de mail sur ton profil, du coup, je passe par les issues. )

Je dois faire un cours similaire et je me demandais combien de temps de cours prend cette initiation ?

L.

**Comment by MrFrangipane** [comment]
Salut,

C'est une initiation que je fais en 5 matinées pour des gens qui n'ont jamais vu de programmation. Je leur conseille de tester la codecademy python avant mon arrivée pour qu'ils aient déjà un tout petit peu tenté de manipuler une console, et qu'ils puissent préparer des questions pour le démarrage.
On parle au début de Python en général (types, variables, fonctions)  et ensuite on applique ça à 3dsMax.  C'est une formation pour les gens qui sont en école de 3D.

 Je vais la modifier un peu prochainement car je donne une semaine de cours dans 15 jours.

Voilà :)

Cordialement,
Val

**Comment by LBdN** [comment]
Ah, on est un peu dans la même situation. Je fais 4 jours complet sur
3dsMax+Python, mais je dois faire toute l'intro python.
Et c'est pour une licence d'infographiste 3d.

Je termine cette semaine, si tu veux mes notes, fais moi signe.

Lionel Barret.

Cordialement,
Lionel Barret,
LBdN Consulting
--------------
http://www.lbdn-consulting.com

2017-01-13 16:41 GMT+01:00 MrFrangipane <notifications@github.com>:
